# Generated by Django 4.2 on 2023-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='directions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('main', 'Main'), ('side', 'Side'), ('dessert', 'Dessert')], default='main', max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no-image.jpg', upload_to='recipes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
