# Generated by Django 4.2 on 2023-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_description_recipe_directions_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.URLField(default='https://liftlearning.com/wp-content/uploads/2020/09/default-image.png'),
        ),
    ]
